let a = 'hello';
console.log(a);
let b = 'owu';
console.log(b);
let c = 'com';
console.log(c);
let d = 'ua';
console.log(d);
let e = 1;
console.log(e);
let f = 10;
console.log(f);
let g = -999;
console.log(g);
let h = 123;
console.log(h);
let k = 3.14;
console.log(k);
let o = 2.7;
console.log(o);
let p = 16;
console.log(p);
let j = true;
console.log(j);
let n = false;
console.log(n);

let firstName = 'Ann';
let middleName = 'Andreevna';
let lastName = 'Bichenko';
let person = `${firstName} ${middleName} ${lastName}`;
console.log(person);

let a = 100;
console.log(typeof a);
let b = '100';
console.log(typeof b);
let c = true;
console.log(c);

